version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: student-management-backend

    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/student-management
      JWT_SECRET: mysecretkey

    depends_on:
      - mongodb

    restart: always


  mongodb:
    image: mongo:7

    container_name: student-management-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    restart: always


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: student-management-frontend

    ports:
      - "8080:80"

    depends_on:
      - backend

    restart: always


volumes:
  mongo-data: